# Generated by Django 2.2.8 on 2021-05-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210512_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
